version: "3.9"
services:

  # Streamlit service
  streamlit:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    command: streamlit run app.py
    volumes:
      - ./dashboard:/dashboard
    ports:
      - "8501:8501"

